name: Continuous Integration Workflow

# This workflow is triggered whenever a new PR is created on the main branch
on:
  pull_request:
    branches:
      - master
    paths:
      - 'crud-mern-frontend/**'
  push:
    branches:
      - master
    paths:
      - 'crud-mern-frontend/**'
  workflow_dispatch:

jobs:

  # Run unit tests to make sure everything is 👍
  test:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
        # Define the working directory for all run steps in the workflow
        working-directory: ./crud-mern-frontend
    # Specify the OS we want the workflow to run on
    runs-on: ubuntu-latest
    # Define the steps for this job
    steps:
    - uses: actions/checkout@v4.1.4
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: npm install
    
    - name: 'Run Tests'
      run: npm run test

  # Run the linter to check for code style issues
  #lint:
  #  name: 'Run linter'
  #  defaults:
  #    run:
  #      shell: bash
        # Define the working directory for all run steps in the workflow
  #      working-directory: ./crud-mern-frontend
  #  runs-on: ubuntu-latest
  #  steps:    
  #  - uses: actions/checkout@v4.1.4
  #    name: 'Checkout repository'
    
  #  - name: 'Install Dependencies'
  #    run: npm install

  #  - name: 'Run Linter'
  #    run: npx standard -v

  # Run the builder to compile the app
  build:
    name: 'Run build'
    defaults:
      run:
        shell: bash
        # Define the working directory for all run steps in the workflow
        working-directory: ./crud-mern-frontend
    # Specify the OS we want the workflow to run on
    runs-on: ubuntu-latest
  
      strategy:
        matrix:
          node-version: [16.x, 18.x, 20.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          
      # Define the steps for this job
      steps:
      - uses: actions/checkout@v4.1.4
        name: 'Checkout repository'
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - run: npm ci
      
      - run: npm run build --if-present

# Run Docker to buid and push images
  docker:
    name: 'Run Docker'
    defaults:
      run:
        shell: bash
        # Define the working directory for all run steps in the workflow
        working-directory: ./crud-mern-frontend
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v4.1.4
      name: 'Checkout repository'

    - name: 'Run Docker'
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ramcastvar/crud-mern-frontend
        registry: docker.io
        #dockerfile: ./crud-mern-frontend/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
